console.log("start");
console.log("am I out of coffee beans? (yes)");
console.log("add coffee beans to shopping list");
console.log("buy coffee beans");
console.log("grind beans");
console.log("is the coffee pot dirty? (yes)");
console.log("clean the pot");
console.log("add filter to coffee machine");
console.log("add coffee grounds to filter");
console.log("add water to coffee machine");
console.log("start coffee maker");
console.log("wait for coffee to finish brewing");
console.log("end");
